### ISSUE TITLE
npm install node-echarts 安装失败

### ISSUE THREAD

**Issue by zhongzhuhua** [hellosean1025/node-echarts#26]
> canvas-prebuilt@1.6.11 install 
> node-pre-gyp install

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: 404 status code downloading tarball https://github.com/chearon/node-canvas-prebuilt/releases/download/v1.6.11/canvas-prebuilt-v1.6.11-node-v72-darwin-x64.tar.gz
node-pre-gyp ERR! stack     at Request.<anonymous>  
prebuilt/node_modules/node-pre-gyp/lib/install.js:137:27)
node-pre-gyp ERR! stack     at Request.emit (events.js:205:15)
node-pre-gyp ERR! stack     at Request.onRequestResponse (node_modules/request/request.js:1066:10)
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:200:13)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:565:23)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:116:17)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:452:22)
node-pre-gyp ERR! stack     at TLSSocket.emit (events.js:200:13)
node-pre-gyp ERR! stack     at addChunk (_stream_readable.js:294:12)
node-pre-gyp ERR! stack     at readableAddChunk (_stream_readable.js:275:11)
node-pre-gyp ERR! System Darwin 17.7.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/node_modules/canvas-prebuilt/node_modules/.bin/node-pre-gyp" "install"
node-pre-gyp ERR! cwd //node_modules/canvas-prebuilt
node-pre-gyp ERR! node -v v12.4.0
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! not ok 
404 status code downloading tarball https://github.com/chearon/node-canvas-prebuilt/releases/download/v1.6.11/canvas-prebuilt-v1.6.11-node-v72-darwin-x64.tar.gz
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas-prebuilt@1.6.11 install: `node-pre-gyp install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the canvas-prebuilt@1.6.11 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/[user]/.npm/_logs/2019-06-17T19_39_11_503Z-debug.log

**Comment by Panpan0403** [comment]
哈喽，请问你解决了吗

**Comment by robert-weiqian** [comment]
您解决问题了吗？急用！！

**Comment by endypark** [comment]
路径错了， 这个应该是源码中，配置错了吧，，我也报错了，哎。

**Comment by hs151991** [comment]
你们这个问题解决了吗，我这安装也是提示这个

**Comment by liulinfen** [comment]
我也出了这个错，后面把node版本降到10.x就好了

**Comment by hanhui** [comment]
大家解决这个问题了吗？
![image](https://user-images.githubusercontent.com/1829623/102003345-19cd8500-3d41-11eb-8ba1-f51757a1316d.png)

**Comment by jsspace** [comment]
node版本10.x可以
