### ISSUE TITLE
docker环境下部署出错-Error loading shared library libpng12.so.0

### ISSUE THREAD

**Issue by yangzhenxiong** [hellosean1025/node-echarts#28]
使用的基础镜像是：alpine
Error: Error loading shared library libpng12.so.0: No such file or directory (needed by /app/node_modules/canvas-prebuilt/canvas/build/Release/canvas.node)
2019/8/28 上午10:23:08 at Object.Module._extensions..node (internal/modules/cjs/loader.js:717:18)
2019/8/28 上午10:23:08 at Module.load (internal/modules/cjs/loader.js:598:32)
2019/8/28 上午10:23:08 at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
2019/8/28 上午10:23:08 at Function.Module._load (internal/modules/cjs/loader.js:529:3)
2019/8/28 上午10:23:08 at Module.require (internal/modules/cjs/loader.js:636:17)
2019/8/28 上午10:23:08 at require (internal/modules/cjs/helpers.js:20:18)
2019/8/28 上午10:23:08 at Object.<anonymous> (/app/node_modules/canvas-prebuilt/canvas/lib/bindings.js:3:18)
2019/8/28 上午10:23:08 at Module._compile (internal/modules/cjs/loader.js:688:30)
2019/8/28 上午10:23:08 at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
2019/8/28 上午10:23:08 at Module.load (internal/modules/cjs/loader.js:598:32)
2019/8/28 上午10:23:08 at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
2019/8/28 上午10:23:08 at Function.Module._load (internal/modules/cjs/loader.js:529:3)
2019/8/28 上午10:23:08 at Module.require (internal/modules/cjs/loader.js:636:17)
2019/8/28 上午10:23:08 at require (internal/modules/cjs/helpers.js:20:18)
2019/8/28 上午10:23:08 at Object.<anonymous> (/app/node_modules/canvas-prebuilt/canvas/lib/canvas.js:13:14)
2019/8/28 上午10:23:08 at Module._compile (internal/modules/cjs/loader.js:688:30)

**Comment by ccmanito** [comment]
您好   我的问题也类似  你解决了吗
