### ISSUE TITLE
Bug occurs when using ，  return process.dlopen(module, path.toNamespacedPath(filename));

### ISSUE THREAD

**Issue by ccmanito** [hellosean1025/node-echarts#30]
## Version
~ 1.1.4

## What is expected
~ 

## Step to reproduce
~ internal/modules/cjs/loader.js:718
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: libpng12.so.0: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:718:18)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/root/node/node_modules/canvas-prebuilt/canvas/lib/bindings.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)

## Environment
~

**Comment by mytingbao** [comment]
I came across the same problem , have you kill it ?
