### ISSUE TITLE
linux 安装失败

### ISSUE THREAD

**Issue by YoLinDeng** [hellosean1025/node-echarts#31]
> canvas-prebuilt@1.6.11 install /home/lightning-service/node_modules/canvas-prebuilt
> node-pre-gyp install

node-pre-gyp WARN Using needle for node-pre-gyp https download 
node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: 404 status code downloading tarball https://github.com/chearon/node-canvas-prebuilt/releases/download/v1.6.11/canvas-prebuilt-v1.6.11-node-v72-linux-x64.tar.gz
node-pre-gyp ERR! stack     at PassThrough.<anonymous> (/home/lightning-service/node_modules/canvas-prebuilt/node_modules/node-pre-gyp/lib/install.js:137:27)
node-pre-gyp ERR! stack     at PassThrough.emit (events.js:205:15)
node-pre-gyp ERR! stack     at ClientRequest.<anonymous> (/home/lightning-service/node_modules/needle/lib/needle.js:482:9)
node-pre-gyp ERR! stack     at Object.onceWrapper (events.js:288:20)
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:200:13)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:565:23)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:116:17)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:452:22)
node-pre-gyp ERR! stack     at TLSSocket.emit (events.js:200:13)
node-pre-gyp ERR! stack     at addChunk (_stream_readable.js:294:12)
node-pre-gyp ERR! System Linux 3.10.0-957.10.1.el7.x86_64
node-pre-gyp ERR! command "/root/.nvm/versions/node/v12.4.0/bin/node" "/home/lightning-service/node_modules/canvas-prebuilt/node_modules/.bin/node-pre-gyp" "install"
node-pre-gyp ERR! cwd /home/lightning-service/node_modules/canvas-prebuilt
node-pre-gyp ERR! node -v v12.4.0
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! not ok 
404 status code downloading tarball https://github.com/chearon/node-canvas-prebuilt/releases/download/v1.6.11/canvas-prebuilt-v1.6.11-node-v72-linux-x64.tar.gz
npm WARN lightning-screenshot-service@1.0.0 No description
npm WARN lightning-screenshot-service@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas-prebuilt@1.6.11 install: `node-pre-gyp install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the canvas-prebuilt@1.6.11 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-11-28T07_07_51_072Z-debug.log

**Comment by zxd9617** [comment]
因为`canvas-prebuilt`已经deprecated，可以参考pull request第一条[migrating from canvas-prebuilt which was deprecated to canvas 2.6.1 and refactoring code](https://github.com/hellosean1025/node-echarts/pull/35)
